version: "3.7"

services:
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - database:/var/lib/postgresql/data/

    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      timeout: 10s
      interval: 5s
      retries: 10

volumes:
  database:
#version: '3'
#
#services:
#  database:
#    image: postgres:latest
#    ports:
#      - 5432:5432
#    env_file:
#      - config/config.yaml
#
#    volumes:
#      - ./db-data/:/var/lib/postgresql/data/
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql