database:
  POSTGRES_HOST: "localhost"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "mysecretpassword"
  POSTGRES_DB: "postgres"
  POSTGRES_PORT: "5432"
  ssl_mode: "disable"
  max_attempts: 5
  pg_url: "postgres://user:pass@localhost:5432/postgres"